# **Introduction to NumPy**

![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMrTWz33b86nfIrgaW9jE_t-7VCcqJtjL-pg&s)

A NumPy array is a powerful data structure in Python provided by the NumPy (Numerical Python) library. It is a grid of values, all of the same type, indexed by a tuple of non-negative integers. Arrays in NumPy are a more efficient and flexible way of storing and manipulating large datasets compared to Python's native lists. They provide support for mathematical operations on arrays, such as element-wise addition, subtraction, multiplication, and division, and offer a range of functions for working with large datasets.

## **Key Features of NumPy Arrays**

- **Efficient storage and operations:** NumPy arrays use less memory and provide faster data processing compared to lists.
- **Homogeneous data types:** All elements of a NumPy array must be of the same data type.
- **Multi-dimensional arrays:** NumPy supports 1D, 2D, and n-dimensional arrays, allowing complex data manipulation.
- **Broadcasting:** Operations on arrays of different shapes can be carried out using a technique called broadcasting.
- **Support for a wide range of functions:** It includes mathematical, logical, linear algebra, Fourier transform, and random number generation functions.

![alt text](https://miro.medium.com/v2/resize:fit:828/1*kM5rQZIpBAjbs7UkqUWJdg.jpeg)

## **Numpy Array Data Type Precedence**

NumPy automatically determines the data type of an array based on the types of the elements in the array. When elements of different data types are combined in an array, NumPy applies data type precedence to convert the elements to a common type. The precedence follows a hierarchy where more general types can encompass less general ones.

Here is the general order of NumPy data type precedence (from lowest to highest precision):

1. Boolean (bool)
2. Integer (int)
3. Unsigned Integer (uint)
4. Float (float)
5. Complex (complex)
6. String (str)
7. Object (object)

## **NumPy Matrix**

Numpy means Numerical Python. The Numpy matrix is a package in Python which is the core scientific computing library. It contains a powerful n-dimensional array object and also enables integrations of C and C++.

The Numpy matrix has a number of uses; from linear algebra to random number capability to its use as a container for generic data.


## **Why use NumPy?**

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

## **NumPy Installation**

All you need to do is type “**pip install numpy**” in the command prompt. This starts the installation. As soon as Numpy is installed go to the **IDE(Integrated Development Environment)** and then import Numpy by typing “**import numpy as np**”.

## **NumPy Array**

A Numpy Array or Numpy matrix is a two-dimensional array that contains both rows and columns. Here’s an example of a NumPy array that has 4 columns and 3 rows.

![numpy array.png](https://miro.medium.com/v2/resize:fit:817/0*y04Nh3L0aSwyGaby.png)

**Single Dimensional Numpy Matrix:**


In [1]:
my_list = [1, 2, 3, 4]
print(type(my_list))

my_dict = {"name": "ravi"}
print(type(my_dict))

<class 'list'>
<class 'dict'>


In [ ]:
import numpy

print(numpy.__version__)

2.2.3


In [3]:
import numpy

my_list = [1, 2, 3, 4]
mat = numpy.array(my_list)
print(type(mat))
print(mat)

<class 'numpy.ndarray'>
[1 2 3 4]


NumPy’s main object is the **homogeneous multidimensional array**. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called **axes**.

For example, the coordinates of a point in 3D space **[1, 2, 1]** has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

```
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
```

**NumPy’s array class is called ndarray**. It is also known by the alias array. Note that **numpy.array** is not the same as the Standard Python Library class **array.array**, which **only handles one-dimensional arrays** and offers less functionality.

**Multi Dimensional Numpy Matrix:**


In [ ]:
import numpy as np  # aliasing

my_list = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]
mat1 = np.array(my_list)
print(type(mat1))

<class 'numpy.ndarray'>


In [5]:
"""
Now let's have a look at the type of mat and mat1
what it will be????
"""

print(type(mat), type(mat1))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
numpy.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

As you can see both instances belongs to **numpy.ndarray** class, where ndarray simply stands for **n-dimensional array**.

## **Attributes of Numpy Array**

The more important attributes of an ndarray object are:

- **ndarray.ndim**

the number of axes (dimensions) of the array.

- **ndarray.shape**

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, the shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

- **ndarray.size**

the total number of elements of the array. This is equal to the product of the elements of shape.

- **ndarray.dtype**

an object describing the type of the elements in the array. One can create or specify dtype using standard Python types. Additionally NumPy provides types of its own. **numpy.int32, numpy.int16, and numpy.float64** are some examples.

- **ndarray.itemsize**

the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to **ndarray.dtype.itemsize**.


Let's jump into examples for everything to understand things in better way...

**1. ndarray.ndim**


In [7]:
import numpy as np


def give_dimension(my_mat):
    print("dimension = ", my_mat.ndim)


give_dimension(np.array([1, 2, 3, 4, 5]))
give_dimension(np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]))
give_dimension(
    np.array(
        [
            [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
            [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
            [[18, 19, 20], [21, 22, 23], [24, 25, 26]],
        ]
    )
)

dimension =  1
dimension =  2
dimension =  3


**2. ndarray.shape**


In [1]:
import numpy as np


def get_shape(my_mat):
    print("(shape/order) = ", my_mat.shape)


get_shape(np.array([1, 2, 3, 4, 5]))
# list of lists
get_shape(np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]))
get_shape(
    np.array(
        [
            [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
            [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
            [[18, 19, 20], [21, 22, 23], [24, 25, 26]],
        ]
    )
)
print(np.array(
        [
            [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
            [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
            [[18, 19, 20], [21, 22, 23], [24, 25, 26]],
        ]
    ))

(shape/order) =  (5,)
(shape/order) =  (2, 5)
(shape/order) =  (3, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


**3. ndarray.size**


In [9]:
import numpy as np


def get_size(my_mat):
    print(f"(size/total number of elements) = ", my_mat.size)


get_size(np.array([1, 2, 3, 4, 5]))
get_size(np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]))
get_size(
    np.array(
        [
            [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
            [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
            [[18, 19, 20], [21, 22, 23], [24, 25, 26]],
        ]
    )
)

(size/total number of elements) =  5
(size/total number of elements) =  10
(size/total number of elements) =  27


**4. ndarray.dtype**


In [11]:
import numpy as np


def data_type(my_matrix):
    print("data type: ", my_matrix.dtype)


data_type(np.array([1.34, 2.45, 1.35, 7.69, 8.56]))
data_type(np.array([4j, 4 + 3j, 6 - 9j]))
data_type(np.array(["a", "b", "c", "abc", "ravipandey", "hiten"]))

data type:  float64
data type:  complex128
data type:  <U10


The Unicode Standard provides a unique number for every character, no matter what platform, device, application or language. It has been adopted by all modern software providers and now allows data to be transported through many different platforms, devices and applications without corruption. Support of Unicode forms the foundation for the representation of languages and symbols in all major operating systems, search engines, browsers, laptops, and smart phones—plus the Internet and World Wide Web (URLs, HTML, XML, CSS, JSON, etc.).


In [11]:
""" you can implicitly define the data type along with array definition.
see the code below ...."""

x = np.array([23, 24.88, 56.9, 78, 97], dtype=np.float16)
x.dtype

dtype('float16')

In [12]:
np.array([1, 2, "3"], dtype=np.float16)

array([1., 2., 3.], dtype=float16)

In [15]:
# this will probably give you an error { the code below }
data_type(np.array(["a", "b", "c", "abc", "vinayak", "hiten"], dtype="complex"))

NameError: name 'data_type' is not defined

**5. ndarray.itemsize**


In [14]:
import numpy as np


def item_size(my_matrix):
    print("item size: ", my_matrix.itemsize, " bytes")


item_size(np.array([1.34, 2.45, 1.35, 7.69, 8.56]))
item_size(np.array([4j, 4 + 3j, 6 - 9j]))
item_size(np.array(["a", "b", "c"], dtype=np.dtype("U8")))

item size:  8  bytes
item size:  16  bytes
item size:  32  bytes


## **NumPy Array Creation**

There are various functions which we can use to create arrays with the help of numpy library. Following code shows the use of those functions to create a single or multi dimensional array.


In [2]:
import numpy as np

# will print array in the range provided as argument
my_np_arr = np.arange(2, 6)
print(my_np_arr)
print(type(my_np_arr), "\n")

# you can also provide spacing between two intervals by providing third argument
print(np.arange(0, -100, -20))  # output is nothing but numpy.ndarray class object

[2 3 4 5]
<class 'numpy.ndarray'> 

[  0 -20 -40 -60 -80]


In [16]:
np.arange(0, -100, -20, dtype=np.float16)

array([  0., -20., -40., -60., -80.], dtype=float16)

In [18]:
my_arr = np.zeros(shape=(4, 5), dtype=np.int8)
print(my_arr.dtype)
print(my_arr, type(my_arr))

int8
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>


In [19]:
np.zeros_like(my_arr)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [15]:
# will print an array of all zeros
print(np.zeros((2, 3)), "\n")

# will print an array of all ones
print(np.ones((2, 2)), "\n")

# will print a constant array
print(np.full(shape=(3, 3), fill_value=9999), "\n")

# will print an identity matrix of provided order
print(np.eye(5), "\n")

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1.]
 [1. 1.]] 

[[9999 9999 9999]
 [9999 9999 9999]
 [9999 9999 9999]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 



In [19]:
"""linspace() will create arrays with a specified number of elements, and spaced 
equally between the specified beginning and end values. 
For example: """

print(np.linspace(3, 3.01, 70))

[3.         3.00014493 3.00028986 3.00043478 3.00057971 3.00072464
 3.00086957 3.00101449 3.00115942 3.00130435 3.00144928 3.0015942
 3.00173913 3.00188406 3.00202899 3.00217391 3.00231884 3.00246377
 3.0026087  3.00275362 3.00289855 3.00304348 3.00318841 3.00333333
 3.00347826 3.00362319 3.00376812 3.00391304 3.00405797 3.0042029
 3.00434783 3.00449275 3.00463768 3.00478261 3.00492754 3.00507246
 3.00521739 3.00536232 3.00550725 3.00565217 3.0057971  3.00594203
 3.00608696 3.00623188 3.00637681 3.00652174 3.00666667 3.00681159
 3.00695652 3.00710145 3.00724638 3.0073913  3.00753623 3.00768116
 3.00782609 3.00797101 3.00811594 3.00826087 3.0084058  3.00855072
 3.00869565 3.00884058 3.00898551 3.00913043 3.00927536 3.00942029
 3.00956522 3.00971014 3.00985507 3.01      ]


In [20]:
np.pi

3.141592653589793

In [24]:
# you can even perform trigonometry on set of values
# trigonometry funtion accepts angle in radians {2 pi = 360 deg}

vals = np.linspace(0, 10 * np.pi, 200)
print(vals)
print()
print(np.sin(vals))
print()
print(np.cos(vals))
print()
print(np.tan(vals))

[ 0.          0.15786898  0.31573796  0.47360693  0.63147591  0.78934489
  0.94721387  1.10508284  1.26295182  1.4208208   1.57868978  1.73655875
  1.89442773  2.05229671  2.21016569  2.36803466  2.52590364  2.68377262
  2.8416416   2.99951057  3.15737955  3.31524853  3.47311751  3.63098648
  3.78885546  3.94672444  4.10459342  4.26246239  4.42033137  4.57820035
  4.73606933  4.8939383   5.05180728  5.20967626  5.36754524  5.52541421
  5.68328319  5.84115217  5.99902115  6.15689013  6.3147591   6.47262808
  6.63049706  6.78836604  6.94623501  7.10410399  7.26197297  7.41984195
  7.57771092  7.7355799   7.89344888  8.05131786  8.20918683  8.36705581
  8.52492479  8.68279377  8.84066274  8.99853172  9.1564007   9.31426968
  9.47213865  9.63000763  9.78787661  9.94574559 10.10361456 10.26148354
 10.41935252 10.5772215  10.73509047 10.89295945 11.05082843 11.20869741
 11.36656638 11.52443536 11.68230434 11.84017332 11.9980423  12.15591127
 12.31378025 12.47164923 12.62951821 12.78738718 12

In [26]:
# import matplotlib.pyplot as plt

# plt.plot(vals, np.sin(vals), label="sin")
# plt.plot(vals, np.cos(vals), label="cos")
# plt.plot(vals, np.tan(vals), label="tan")
# plt.legend()

In [30]:
# from PIL import Image

# Image.fromarray(np.full((100, 100), fill_value=120, dtype=np.uint8))

## **Random Numbers in NumPy**

### **What is a Random Number?**

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

### **Pseudo Random and True Random**

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well. If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

### **Can we make truly random numbers?**

**Yes**. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our **keystrokes, mouse movements, data on network etc**.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).


### **Generate Random Number**

NumPy offers the **random modul**e to work with random numbers.

**1. Generate a random integer from 0 to 100:**


In [22]:
# everything is pseudo random
from numpy import random

x = random.randint(900, 1000)

print(x)

992


**2. The random module's rand() method returns a random float between 0 and 1.**


In [23]:
from numpy import random

x = random.randn(3, 4)
y = x.astype(np.float16)

print(x, x.dtype)

[[ 0.14416274 -0.01197786  0.70727972  0.46736814]
 [ 0.23473322 -0.52345685 -0.6854665  -0.83818759]
 [ 0.04522576 -0.02190861 -1.59632689  1.08070878]] float64


### **Generate Random Array**

In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

**Integers**

The **randint()** method takes a **size** parameter where you can specify the shape of an array.


In [24]:
from numpy import random

x = random.randint(1000, size=(5, 3))

print(x, x.ndim, x.shape)

[[845 906  28]
 [852 317 707]
 [770  37 262]
 [866 610  33]
 [226 309 221]] 2 (5, 3)


**Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:**


In [54]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[54 75 36 20 56]
 [51 85  4 19 62]
 [89 11 18 99 55]]


**Floats**

The **rand()** method also allows you to specify the shape of the array.

**Generate a 1-D array containing 5 random floats:**


In [65]:
from numpy import random

x = random.rand(5, 3)

print(x)

[[0.79148038 0.04326693 0.33904778]
 [0.99509356 0.39690945 0.92941587]
 [0.00448856 0.52005001 0.60526339]
 [0.75054312 0.38205185 0.01012318]
 [0.28113173 0.60482237 0.22623092]]


**Generate a 2-D array with 3 rows, each row containing 5 random numbers:**


In [66]:
from numpy import random

x = random.rand(3, 5)

print(x, x.shape)

[[0.24302219 0.6659257  0.75206741 0.8948992  0.12993945]
 [0.98791221 0.69304124 0.25194538 0.8430505  0.09999859]
 [0.52574364 0.84938856 0.7790512  0.25594738 0.49807913]] (3, 5)


### **Generate Random Number From Array**

The **choice()** method allows you to generate a random value based on an array of values.

The **choice()** method takes an array as a parameter and randomly returns one of the values.


In [82]:
import random

random.choice([1, 2, 3])

1

In [83]:
from numpy import random

x = random.choice([3, 5, 7, 9, 6373])

print(x)

9


The choice() method also allows you to return an array of values. Add a **size** parameter to specify the shape of the array.

**Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):**


In [86]:
from numpy import random

x = random.choice([3, 5, 7, 9, 87, 1002], size=(3, 2, 3))

print(x)

[[[   5    9 1002]
  [1002    5    9]]

 [[   9 1002    7]
  [   9   87    3]]

 [[   5    7 1002]
  [   7    9 1002]]]


In [91]:
x = [1, 2, 3, 4, 5]
x[0:3]

[1, 2, 3]

### **NumPy Array Indexing**

Numpy offers several ways to index into arrays.


In [ ]:
# slicing operator - :

In [90]:
my_lst = [1, 3, 45, 56, 54]
print(my_lst[1:-1])

[3, 45, 56]


In [97]:
import numpy as np

xmat = np.array([[23, 45, 67, 78], [34, 56, 89, 90], [23, 24, 45, 68]])
print(type(xmat))  # will get the class name
print(xmat, "\n")


""" consider the array as a matrix and think about the 
first term 23 in terms of
x and y position index starting from 0"""

# so to access first term of the matrix we'll write
print(xmat[0][0])  # 0th row and 0th column

# to access entire matrix let's quickly go through the code below
for i in range(0, xmat.shape[0]):
    for j in range(0, xmat.shape[1]):
        print(xmat[i, j], end=" ")

<class 'numpy.ndarray'>
[[23 45 67 78]
 [34 56 89 90]
 [23 24 45 68]] 

23
23 45 67 78 34 56 89 90 23 24 45 68 

In [99]:
xmat[0][0]

23

**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:


In [34]:
import numpy as np

xmat = np.array([[23, 45, 67, 78], [34, 56, 89, 90], [23, 24, 45, 68]])

print(xmat)

print()

# to print first two rows and first two columns
print(xmat[1, 1:3], "\n")

temp = xmat[1, 1:3]
print(temp.ndim)

# to print entire columns and first row only
print(xmat[:1, :], "\n")

# to print entire rows and first two columns
print(xmat[:, :2])

[[23 45 67 78]
 [34 56 89 90]
 [23 24 45 68]]

[56 89] 

1
[[23 45 67 78]] 

[[23 45]
 [34 56]
 [23 24]]


**Note [IMPORTANT]:** You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.


In [102]:
import numpy as np

xmat = np.array([[23, 45, 67, 78], [34, 56, 89, 90], [23, 24, 45, 68]])
print(f"original mat =>\n{xmat}")

""" there is not only one way to get the second row.
see the code below"""

print('step 2')
print(xmat[1, :])
print('step 3')
print(xmat[1:2, :])

# then what is the difference??
# see the output correctly you will get to know
# using mixing of integer and slicing as parameter in xmat[]
# yields an array of lower rank while using slicing only
# will give an array of the same rank as the original matrix.

print(xmat[1, :].shape)  # rank = 1
print(xmat[1:2, :].shape)  # rank = 2

original mat =>
[[23 45 67 78]
 [34 56 89 90]
 [23 24 45 68]]
step 2
[34 56 89 90]
step 3
[[34 56 89 90]]
(4,)
(1, 4)


**Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:


In [107]:
fruits = ['apple', 'mango', 'banana']
colors = ['red', 'oraange', 'yellow', 'violet']
names = ['ravi', 'vinayak', 'hiten']
for i in range(0, len(fruits)):
    print(f'{fruits[i]} is {colors[i]}')
    
print('----')
for fruit, color, name in zip(fruits, colors, names):
    print(f'{fruit} is {color} - {name}')

apple is red
mango is oraange
banana is yellow
----
apple is red - ravi
mango is oraange - vinayak
banana is yellow - hiten


In [97]:
a = [1, 2, 3, 3]
b = [1, 4, 9, 4]
c = [2, 3, 4, 5, 6]

for element in zip(a, b, c):
    print(element)

(1, 1, 2)
(2, 4, 3)
(3, 9, 4)
(3, 4, 5)


In [98]:
import numpy as np

a = np.array([[1, 4, 5], [2, 3, 6], [4, 7, 9]])

print(a)

# this will print the diagonal elements of the matrix

print(a[[0, 1, 2], [0, 1, 2]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 2]]))  # Prints "[1 3 9]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[4 4]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[4 4]"

[[1 4 5]
 [2 3 6]
 [4 7 9]]
[1 3 9]
[1 3 9]
[4 4]
[4 4]


### **Array Maths**

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:


In [114]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float32)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Element Wise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
# print(x.__add__(y), "\n")
print(np.add(x, y), "\n")

# Element Wise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y), "\n")

# Element Wise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y), "\n")

# Element Wise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y), "\n")

# Element Wise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))
print(np.square(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]] 

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]] 

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[1.        1.4142135]
 [1.7320508 2.       ]]
[[ 1.  4.]
 [ 9. 16.]]


**Note:** \* is element wise multiplication, not matrix multiplication. We instead use the **dot function** to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:


In [123]:
import numpy as np

# matrix
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])


"""

[1, 2]
[3, 4] 

[9, 10]


"""
# vectors
v = np.array([9, 10])
w = np.array([11, 12])

# print(v, w)

# print(v.shape)

# Inner product of vectors; both produce 219
# vector x vector = scaler value
# print(v.dot(w))
# print(np.dot(v, w), "\n")

# # Matrix / vector product; both produce the rank 1 array [29 67]
# # (2, 2) (2,) => (2,)
# print(x, v)
# print(x.dot(v))
# print(np.dot(x, v), "\n")

# # Matrix / matrix product; both produce the rank 2 array
# # [[19 22]
# #  [43 50]]
# (2, 2) (2, 2) => (2, 2)
print(x.dot(y))
print(np.dot(x, y))

# 1d *1d -> scaler value
# 2d * 1d -> 1d
# nd * nd -> matrix

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is **sum**:


In [126]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the **T** attribute of an array object:


In [127]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
print(x)
# Prints "[[1 2]
#          [3 4]]"
print(x.T)
# Prints "[[1 3]
#          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1, 2, 3])
print(v)  # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### **Array manipulation routines**

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like **Pandas** are built around the NumPy array. We will present several examples of using NumPy array manipulation to **access data and subarrays, and to split, reshape, and join the arrays**. While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples.

**Example 1:** To copy one array from source to destination you can make use of fucntion

**numpy.copyto:**

Copies values from one array to another, broadcasting as necessary.

Raises a **TypeError** if the casting rule is violated, and if **where** is provided, it selects which elements to copy.

**where:--** A boolean array which is broadcasted to match the dimensions of destination, and selects elements to **copy from source to destination** wherever it contains the value **True**.


In [123]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [132]:
import numpy as np

my_arr = np.array([1, 3, 4, 7, 8], dtype=np.int32)
my_arr_2 = np.array([2, 4.6, 6, 78, 89], dtype=np.float32)


# first parameter should be destinbation and second should be source
np.copyto(my_arr_2, my_arr, casting="same_kind")
print(my_arr_2)

"""
make sure both arrays should have same data types or else it will 
raise an error
and to avoid this kind of error you can set one of the parameter 
provided with 
numpy.copyto and that is casting = 'unsafe'. By default the parameter 
value is 
'same_kind' which means of same data type.
"""

[1. 3. 4. 7. 8.]


"\nmake sure both arrays should have same data types or else it will \nraise an error\nand to avoid this kind of error you can set one of the parameter \nprovided with \nnumpy.copyto and that is casting = 'unsafe'. By default the parameter \nvalue is \n'same_kind' which means of same data type.\n"

### **Changing Array Shape**

Changing shape of an array plays an important role when you are dealing with multidimensional data, data from images and many more things. There are various ways to change shape of an array and we will see many examples over that.

**1. numpy.reshape: --** Gives a new shape to an array without changing its data.

**2. numpy.ravel: --** Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

**3. numpy.flatten: --** Return a copy of the array collapsed into one dimension.

**Example 2:**


In [25]:
my_mat = np.array([[34, 1, 2, 4, 5, 6], [56, 45, 7, 89, 654, 54]])
print(my_mat.shape, my_mat)

(2, 6) [[ 34   1   2   4   5   6]
 [ 56  45   7  89 654  54]]


In [135]:
# make sure size must be same after performing reshape
np.reshape(my_mat, (3, 4))

array([[ 34,   1,   2,   4],
       [  5,   6,  56,  45],
       [  7,  89, 654,  54]])

In [27]:
np.array([1, 2, 3, 4,5,6]).reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
my_flatten = np.ravel(np.random.randint(10, size=(3, 4, 5, 34, 34)))
print(my_flatten.ndim)

1


In [144]:
# here look carefully we need to reference ndarray with flatten function not
# with numpy

t = my_mat.flatten()
print(t)

[ 34   1   2   4   5   6  56  45   7  89 654  54]


### **Transpose-like operations**

**1. numpy.moveaxis:--** Move axes of an array to new positions. Other axes remain in their original order.

**2. numpy.rollaxis:--** Roll the specified axis backwards, until it lies in a given position. This function continues to be supported for backward compatibility, but you should prefer moveaxis.

**3. numpy.swapaxes:--** Interchange two axes of an array.

**Example 3:**


**numpy.moveaxis(a, source, destination)**


In [22]:
x = np.zeros((3, 4, 5))
print(x)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [24]:
x1 = np.moveaxis(x, 0, -1)
print(x1.shape)
print(x1)

(4, 5, 3)
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## take this function again with good example

**numpy.rollaxis(a, axis, start=0)**

When **start <= axis**, the axis is rolled back until it lies in this position. When **start > axis**, the axis is rolled until it lies before the mentioned position. The default, 0, results in a “complete” roll.


In [25]:
import numpy as np

a = np.ones((3, 4, 5, 6, 7))
a

array([[[[[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

        

In [26]:
# 3, 4, 5, 6, 7
# 7 -> axis
# 6 -> start
# start <= axis


np.rollaxis(a, 4, 3).shape

(3, 4, 5, 7, 6)

In [27]:
# 3, 4, 5, 6, 7
# 5 -> axis
# 3 -> start
# start <= axis

np.rollaxis(a, 2, 0).shape

(5, 3, 4, 6, 7)

In [ ]:
# 3, 4, 5, 6, 7
# 4 -> axis
# 7 -> start
# start <= axis -> False


"""
3 4 5 6 7
3 5 4 6 7
3 5 6 4 7
"""

np.rollaxis(a, 1, 4).shape

(3, 5, 6, 4, 7)

**numpy.swapaxes(a, axis1, axis2)**


In [29]:
x = np.array([[1, 2, 3]])
print(x.shape)

x_swapped = np.swapaxes(x, 0, 1)
print(x_swapped)
print(x_swapped.shape)

(1, 3)
[[1]
 [2]
 [3]]
(3, 1)


In [30]:
x = np.zeros((3, 5, 4))
x.swapaxes(0, 2).shape

(4, 5, 3)

### **Joining arrays**

**1. numpy.concatenate:--** Join a sequence of arrays along an existing axis.

**2. numpy.stack:--** Join a sequence of arrays along a new axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension. hstack, vsrtack, dstack many more are there which works in the same way stack does. For more info, you can search on google.

**Example 4:**


**numpy.concatenate((a1, a2, ...), axis=0, out=None)**

out: If provided, the destination to place the result


In [33]:
a = np.array([[1, 2, 4], [3, 4, 4]])
b = np.array([[5, 6, 6]])

print(a.shape, b.shape)
np.concatenate((a, b), axis=0)

(2, 3) (1, 3)


array([[1, 2, 4],
       [3, 4, 4],
       [5, 6, 6]])

In [57]:
b, b.T

(array([[5, 6]]),
 array([[5],
        [6]]))

In [58]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

**numpy.stack(arrays, axis=0, out=None)**


In [34]:
# list comprehension
[x * x for x in range(10)]  # -> [0, 1, 2 3, ..., 9]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [41]:
arrays = np.array([np.random.rand(3, 4) for i in range(12)])
arrays.shape

(12, 3, 4)

In [45]:
np.stack((arrays, arrays), axis=2).shape

(12, 3, 2, 4)

In [62]:
out1 = np.stack(arrays, axis=1)
print(out1, out1.shape)
# print(np.stack(arrays, axis=2).shape)

[[[0.41117393 0.09288245 0.81632723 0.13114693]
  [0.0882312  0.36808019 0.02284409 0.37442682]
  [0.6562185  0.01579776 0.7453767  0.75338106]
  [0.27127701 0.80546745 0.48992999 0.06768014]
  [0.56587411 0.4133055  0.33546775 0.96410304]
  [0.91935842 0.14104538 0.91162853 0.54339694]
  [0.17501499 0.37759294 0.18485919 0.44622604]
  [0.47893632 0.08342001 0.89193221 0.56939813]
  [0.83625434 0.65926922 0.2328728  0.56288284]
  [0.68756041 0.87386306 0.11354758 0.84425563]]

 [[0.67446469 0.56259138 0.2512961  0.55181421]
  [0.08289145 0.88668121 0.83210412 0.43036911]
  [0.55626191 0.01620583 0.82821436 0.65963154]
  [0.26272842 0.19811873 0.10314968 0.57197235]
  [0.3503785  0.05319808 0.56472508 0.4881179 ]
  [0.74240805 0.88627658 0.62740472 0.44525859]
  [0.32292601 0.01007856 0.5320702  0.36375172]
  [0.93250806 0.65382649 0.48665715 0.91281992]
  [0.7911887  0.13305446 0.9353591  0.36523825]
  [0.39779114 0.64512516 0.8796501  0.41842011]]

 [[0.28714624 0.8118639  0.4776902  

In [63]:
print(np.stack(arrays, axis=2))
print()
print(np.stack(arrays, axis=2).shape)

[[[0.41117393 0.0882312  0.6562185  0.27127701 0.56587411 0.91935842
   0.17501499 0.47893632 0.83625434 0.68756041]
  [0.09288245 0.36808019 0.01579776 0.80546745 0.4133055  0.14104538
   0.37759294 0.08342001 0.65926922 0.87386306]
  [0.81632723 0.02284409 0.7453767  0.48992999 0.33546775 0.91162853
   0.18485919 0.89193221 0.2328728  0.11354758]
  [0.13114693 0.37442682 0.75338106 0.06768014 0.96410304 0.54339694
   0.44622604 0.56939813 0.56288284 0.84425563]]

 [[0.67446469 0.08289145 0.55626191 0.26272842 0.3503785  0.74240805
   0.32292601 0.93250806 0.7911887  0.39779114]
  [0.56259138 0.88668121 0.01620583 0.19811873 0.05319808 0.88627658
   0.01007856 0.65382649 0.13305446 0.64512516]
  [0.2512961  0.83210412 0.82821436 0.10314968 0.56472508 0.62740472
   0.5320702  0.48665715 0.9353591  0.8796501 ]
  [0.55181421 0.43036911 0.65963154 0.57197235 0.4881179  0.44525859
   0.36375172 0.91281992 0.36523825 0.41842011]]

 [[0.28714624 0.80382144 0.58921586 0.39594074 0.77411837 0.

### **Adding and removing elements**

**1. numpy.delete:--** Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

**2. numpy.insert:--** Insert values along the given axis before the given indices.

**3. numpy.append:--** Append values to the end of an array.

**Example 5:**


**numpy.delete(arr, obj, axis=None)**

axis: The axis along which to delete the subarray defined by obj. If axis is None, obj is applied to the flattened array.


In [65]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
# 2 - which axis
# 1 - how row/column
np.delete(arr, 2, 1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

**numpy.insert(arr, obj, values, axis=None)**

axis: Axis along which to insert values. If axis is None then arr is flattened first.


In [69]:
a = [1, 5, 1, 2, 2, 3, 3]

In [70]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [73]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [85]:
np.insert(a, 1, 5, axis=0)

array([[1, 1],
       [5, 5],
       [2, 2],
       [3, 3]])

In [80]:
np.insert(a, [1], [[1], [2], [3]], axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

**numpy.append(arr, values, axis=None)**


In [74]:
x = [[1, 2, 3], [4, 5, 6]]
np.append(x, [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## ignore

### **NumPy Linear Algebra**

The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.

**One can find:**

- rank, determinant, trace, etc. of an array.
- eigen values of matrices
- matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
- solve linear or tensor equations and much more!

#### **Matrix and vector products**

**1. numpy.dot:--** Dot product of two arrays.

**2. numpy.linalg.multi_dot:--** Compute the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order.

**3. numpy.vdot:--** Return the dot product of two vectors.

**4. numpy.inner:--** Inner product of two arrays. Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

**5. numpy.outer:--** Compute the outer product of two vectors.

Given two vectors, **a = [a0, a1, ..., aM]** and **b = [b0, b1, ..., bN]**, the outer product is:

```
[[a0*b0  a0*b1 ... a0*bN ]
 [a1*b0    .
 [ ...          .
 [aM*b0            aM*bN ]]
```

**6. numpy.matmul:--** Matrix product of two arrays.

**Example 1:**


**numpy.dot(a, b, out=None)**

Raises
**ValueError**
If the last dimension of a is not the same size as the second-to-last dimension of b.


In [76]:
print(np.dot(3, 4))
print(np.dot([2, 3], [2, 3]))

12
13


In [78]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [ ]:
a = np.arange(3 * 4 * 5 * 6).reshape((3, 4, 5, 6))
b = np.arange(3 * 4 * 5 * 6)[::-1].reshape((5, 4, 6, 3))
np.dot(a, b)[2, 3, 2, 1, 2, 2]

499128

**numpy.linalg.multi_dot(arrays, \*, out=None)**


In [79]:
from numpy.linalg import multi_dot

# Prepare some data
A = np.random.random((20, 10))
B = np.random.random((10, 7))
C = np.random.random((7, 5))
D = np.random.random((5, 2))

# the actual dot multiplication
result = multi_dot([A, B, C, D])
print(result)

[[17.90823495 17.39484665]
 [18.87874951 18.32104311]
 [21.88582943 21.2577101 ]
 [22.51283124 22.10582949]
 [17.55226946 17.24789444]
 [16.24712687 15.96851089]
 [14.81762439 14.42752387]
 [14.47251634 14.15660414]
 [17.20095817 16.9369507 ]
 [21.47350097 20.96062714]
 [22.15847986 21.77888951]
 [14.82060748 14.54702486]
 [20.78183986 20.31704332]
 [14.46793193 13.97839963]
 [24.2457535  23.57723923]
 [28.37922771 27.54928157]
 [22.37970428 21.9303718 ]
 [19.35632554 18.95671722]
 [22.99512373 22.56209736]
 [14.38095726 14.00771746]]


**numpy.vdot(a, b)**


In [80]:
a = np.array([1 + 2j, 3 + 4j])
b = np.array([5 + 6j, 7 + 8j])
np.vdot(a, b)

(70-8j)

In [ ]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
np.vdot(a, b)

30

**numpy.inner(a, b)**

out.shape = a.shape[:-1] + b.shape[:-1]


In [81]:
a = np.array([1, 2, 3])
print(a.shape)
b = np.array([0, 1, 0])
print(b.shape)
res = np.inner(a, b)
print(res, res.shape)

(3,)
(3,)
2 ()


In [82]:
a = np.arange(12).reshape((2, 3, 2))
print(a)
print()

b = np.arange(2)
print(b)
print()

print(np.inner(a, b))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

[0 1]

[[ 1  3  5]
 [ 7  9 11]]


**numpy.outer(a, b)**


In [83]:
np.linspace(-2, 2, 5)

array([-2., -1.,  0.,  1.,  2.])

In [84]:
np.outer(np.ones((5,)), np.linspace(-2, 2, 5))

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

**numpy.matmul**

**ValueError**
If the last dimension of a is not the same size as the second-to-last dimension of b.


In [89]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])
np.dot(a, c).shape

(9, 5, 7, 9, 5, 3)

In [90]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

### **Matrix eigenvalues**

**1. numpy.linalg.eig:--** Compute the eigenvalues and right eigenvectors of a square array.

**2. numpy.linalg.eigh:--** Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix. Returns two objects, a 1-D array containing the eigenvalues of a, and a 2-D square array or matrix (depending on the input type) of the corresponding eigenvectors (in columns).

**3. numpy.linalg.eigvals:--** Compute the eigenvalues of a general matrix.

**4. numpy.linalg.eigvalsh:--** Compute the eigenvalues of a complex Hermitian or real symmetric matrix.

**Example 2:**


**numpy.linalg.eig(a)**


In [ ]:
from numpy import linalg as la

a = np.random.randn(2, 2)
print(a, "\n")
eigen_vals, eigen_vects = la.eig(a)

print(eigen_vals)
print()
print(eigen_vects)

[[ 0.63873273  2.08129531]
 [-0.13162044  0.91463705]] 

[0.77668489+0.50488634j 0.77668489-0.50488634j]

[[0.96980499+0.j         0.96980499-0.j        ]
 [0.06428049+0.23525796j 0.06428049-0.23525796j]]


**numpy.linalg.eigh(a)**


In [ ]:
from numpy import linalg as la

a = np.array([[1, -2j], [2j, 5]])
print(a, "\n")
eigen_vals, eigen_vects = la.eigh(a)

print(eigen_vals)
print()
print(eigen_vects)

[[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]] 

[0.17157288 5.82842712]

[[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


**numpy.linalg.eigvals(a)**

Main difference between eigvals and eig: the eigenvectors aren’t returned.


In [ ]:
a = np.random.randn(2, 2)
print(a, "\n")
la.eigvals(a)

[[-0.06227234 -0.36712736]
 [ 1.62956979  0.15919536]] 



array([0.04846151+0.76550484j, 0.04846151-0.76550484j])

**numpy.linalg.eigvalsh(a)**

Main difference from eigh: the eigenvectors are not computed.


In [ ]:
a = np.array([[1, -2j], [2j, 5]])
print(a, "\n")
la.eigvalsh(a)

[[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]] 



array([0.17157288, 5.82842712])

### **Summary:**

Not just linear algebra but many mathematical operations we can perfrom using numpy library and we have studied the way numpy computes the array, creates the array, manipulates the shape, performs mathematical operations on it. After this whenever new concepts will come we will learn more about numpy library contents so that we will better understand where to use what.
